### ISSUE TITLE
Debian Support

### ISSUE THREAD

**Issue by Dosenpfand** [lafranceinsoumise/ansible-backup#11]
Hi,
The role looks really great, thanks for publishing it. Since I am using Debian, I would like to add support for it. Would this be of interest? If so, I could work on a pull request.

Cheers!

**Comment by jillro** [comment]
Hello !

Thanks, but we are not 100% sure we will have time to maintain the role for Debian in the future. We do not want to add a feature we cannot maintain, so we prefer to stick to Ubuntu, the system we are using at @lafranceinsoumise. Sorry.
