### ISSUE TITLE
possible dependency conflict on 18.04

### ISSUE THREAD

**Issue by jillro** [lafranceinsoumise/ansible-backup#2]
https://github.com/lafranceinsoumise/ansible-backup tests are only run on 16.04, so this may be possible that there is a dependency conflict on 18.04. This is a case in https://github.com/guilro/trellis-backup-role/issues/23 but I could not reproduce on a 18.04 Scaleway box when installing manually the packages with apt.

@smaboshe could you indicate your box provider ?

**Comment by smaboshe** [comment]
Thanks, @guilro. I am using `bento/ubuntu-18.04` and also get the error on an AWS Ubuntu 18.04 virtual machine.

**Comment by evilhamsterman** [comment]
I think you problem is actually this upstream Ubuntu bug https://bugs.launchpad.net/ubuntu/+source/python-boto/+bug/1808773

**Comment by smaboshe** [comment]
Thanks, @evilhamsterman. I'll keep an eye on that bug.
