### ISSUE TITLE
There seems to be no restore script in duply

### ISSUE THREAD

**Issue by Xilonz** [lafranceinsoumise/ansible-backup#9]
I've been trying to find out why my [restore (the bash script)](https://github.com/lafranceinsoumise/ansible-backup/blob/master/templates/restore.j2) doesn't execute and there seems no reference to this file in the duply script and/or documentation.

I expected it to work like: `duply profile_database restore dump` and it then to restore the sql?

**Comment by jillro** [comment]
It works like this, whats your output with this command ?

**Comment by Xilonz** [comment]
```
Start duply v1.11, time is 2020-03-30 13:41:39.
Using profile '/etc/duply/example.com_database'.
Using installed duplicity version 0.7.19, python 2.7.12, gpg 1.4.20 (Home: ~/.gnupg), awk 'GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)', grep 'grep (GNU grep) 2.25', bash '4.3.48(1)-release (x86_64-pc-linux-gnu)'.
Checking TEMP_DIR '/tmp' is a folder and writable (OK)
Test - En/Decryption skipped. (GPG disabled)

--- Start running command RESTORE at 13:41:39.790 ---
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Wed Mar 11 01:02:40 2020
--- Finished state OK at 13:41:42.882 - Runtime 00:00:03.092 -
```

And with the -v6 it only shows progress information like:
```
...
WebDAV GET /remote.php/webdav/trellis/example.com/database/duplicity-inc.20200321T010133Z.to.20200322T010200Z.vol1.difftar.gz request with headers: {'Connection': 'keep-alive', 'Authorization': 'Basic YmFja3VwOmFQcG8yWEk3SHo0NnlC'}
WebDAV data length: 4
WebDAV response status 200 with reason 'OK'.
Deleting /tmp/duplicity-IdUmA4-tempdir/mktemp-aC28KN-2
Processed volume 1 of 12
Deleting /tmp/duplicity-IdUmA4-tempdir/mktemp-cw9cL0-3
...
```

**Comment by jillro** [comment]
It seems to work perfectly. Now you just need to restore the dump to your database with `mysql databasename < dump.sql` (the command may vary depending on role access to database).

**Comment by Xilonz** [comment]
Yes, correct, but that seems to be what the restore script wat intended for.

https://github.com/lafranceinsoumise/ansible-backup/blob/master/templates/restore.j2 templates out to:
```
#!/bin/bash

# This file was generated by Ansible for example.vps.com
# Do NOT modify this file by hand!

WORKDIR=/var/duply/example.com_database


# Restore the passed database
DBNAME=example_com_production
mysql   $DBNAME  < ${WORKDIR}/dump
rm -rf $WORKDIR/dump
```

But this code never seems to be firing? It's not documented in this repo nor duply. 
I can fire this manually, but it looks like its supposed to run automatically. 

If its indented to run manually, I'll do a pr to add it to the readme :)

**Comment by jillro** [comment]
Actually I didn't even remember this file was created.

Yes, Duply never run any script on restore. Restore scripts would typically have destructive effects, and restore operations should never be destructive. You should always restore manually to an empty directory, check your data, and re-importit if necessary.

**Comment by jillro** [comment]
Fixed this in the README. But I wonder if duply didn't drop restore script support, because I am pretty sure I used to run `duply profile restore` without indicating a destination because this was handled by the restore script, and now destination is mandatory.

**Comment by Xilonz** [comment]
Yea, I did do some research but couldn't find anything. Ty for clarifying!
